import type { Snippet } from "svelte";
import type { Activity, ActivityDisplaySummary } from "../domain/activity";
import type { MetricSeriesResponse } from "../components/metric-series";
import type { DesignLanguage } from "../theme/themes";

export type ActivityThemeProps = {
  activities: Activity[];
  displaySummary: ActivityDisplaySummary | null;
  summaryLoading: boolean;
  summaryError: string | null;
  summaryDistanceUnknownCount: number;
  boundsError: string | null;
  boundsLoading: boolean;
  onRetryBounds: () => Promise<void>;
  summaryScope: string;
  recordsScope: string;
  recordsReady: boolean;
  onRetrySummary: () => Promise<void>;
  onRetryRecords: () => Promise<void>;
  onRetrySeries: () => Promise<void>;
  sportType: string;
  sportOptions: string[];
  loading: boolean;
  error: string | null;
  hasMore: boolean;
  loadingMore: boolean;
  loadMoreError?: string | null;
  onSportType: (value: string) => void;
  onLoadMore: () => void | Promise<void>;
  onOpenDetail: (id: string) => void;
  activitySeries?: MetricSeriesResponse | null;
  activityDurationSeries?: MetricSeriesResponse | null;
  activitySeriesLoading?: boolean;
  activitySeriesError?: string | null;
  activitySeriesScope?: string;
  theme: DesignLanguage;
  children?: Snippet;
};
