/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** OpenAPI description (this document) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/activities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    id?: components["parameters"]["rowFilter.activities.id"];
                    sport_type?: components["parameters"]["rowFilter.activities.sport_type"];
                    title?: components["parameters"]["rowFilter.activities.title"];
                    started_at?: components["parameters"]["rowFilter.activities.started_at"];
                    ended_at?: components["parameters"]["rowFilter.activities.ended_at"];
                    timezone?: components["parameters"]["rowFilter.activities.timezone"];
                    distance_m?: components["parameters"]["rowFilter.activities.distance_m"];
                    duration_s?: components["parameters"]["rowFilter.activities.duration_s"];
                    moving_time_s?: components["parameters"]["rowFilter.activities.moving_time_s"];
                    elevation_gain_m?: components["parameters"]["rowFilter.activities.elevation_gain_m"];
                    avg_hr?: components["parameters"]["rowFilter.activities.avg_hr"];
                    max_hr?: components["parameters"]["rowFilter.activities.max_hr"];
                    avg_pace_s_per_km?: components["parameters"]["rowFilter.activities.avg_pace_s_per_km"];
                    /** @description Filtering Columns */
                    select?: components["parameters"]["select"];
                    /** @description Ordering */
                    order?: components["parameters"]["order"];
                    /** @description Limiting and Pagination */
                    offset?: components["parameters"]["offset"];
                    /** @description Limiting and Pagination */
                    limit?: components["parameters"]["limit"];
                };
                header?: {
                    /** @description Limiting and Pagination */
                    Range?: components["parameters"]["range"];
                    /** @description Limiting and Pagination */
                    "Range-Unit"?: components["parameters"]["rangeUnit"];
                    /** @description Preference */
                    Prefer?: components["parameters"]["preferCount"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["activities"][];
                        "application/vnd.pgrst.object+json;nulls=stripped": components["schemas"]["activities"][];
                        "application/vnd.pgrst.object+json": components["schemas"]["activities"][];
                        "text/csv": components["schemas"]["activities"][];
                    };
                };
                /** @description Partial Content */
                206: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: {
                    /** @description Filtering Columns */
                    select?: components["parameters"]["select"];
                };
                header?: {
                    /** @description Preference */
                    Prefer?: components["parameters"]["preferPost"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: components["requestBodies"]["activities"];
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete: {
            parameters: {
                query?: {
                    id?: components["parameters"]["rowFilter.activities.id"];
                    sport_type?: components["parameters"]["rowFilter.activities.sport_type"];
                    title?: components["parameters"]["rowFilter.activities.title"];
                    started_at?: components["parameters"]["rowFilter.activities.started_at"];
                    ended_at?: components["parameters"]["rowFilter.activities.ended_at"];
                    timezone?: components["parameters"]["rowFilter.activities.timezone"];
                    distance_m?: components["parameters"]["rowFilter.activities.distance_m"];
                    duration_s?: components["parameters"]["rowFilter.activities.duration_s"];
                    moving_time_s?: components["parameters"]["rowFilter.activities.moving_time_s"];
                    elevation_gain_m?: components["parameters"]["rowFilter.activities.elevation_gain_m"];
                    avg_hr?: components["parameters"]["rowFilter.activities.avg_hr"];
                    max_hr?: components["parameters"]["rowFilter.activities.max_hr"];
                    avg_pace_s_per_km?: components["parameters"]["rowFilter.activities.avg_pace_s_per_km"];
                };
                header?: {
                    /** @description Preference */
                    Prefer?: components["parameters"]["preferReturn"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch: {
            parameters: {
                query?: {
                    id?: components["parameters"]["rowFilter.activities.id"];
                    sport_type?: components["parameters"]["rowFilter.activities.sport_type"];
                    title?: components["parameters"]["rowFilter.activities.title"];
                    started_at?: components["parameters"]["rowFilter.activities.started_at"];
                    ended_at?: components["parameters"]["rowFilter.activities.ended_at"];
                    timezone?: components["parameters"]["rowFilter.activities.timezone"];
                    distance_m?: components["parameters"]["rowFilter.activities.distance_m"];
                    duration_s?: components["parameters"]["rowFilter.activities.duration_s"];
                    moving_time_s?: components["parameters"]["rowFilter.activities.moving_time_s"];
                    elevation_gain_m?: components["parameters"]["rowFilter.activities.elevation_gain_m"];
                    avg_hr?: components["parameters"]["rowFilter.activities.avg_hr"];
                    max_hr?: components["parameters"]["rowFilter.activities.max_hr"];
                    avg_pace_s_per_km?: components["parameters"]["rowFilter.activities.avg_pace_s_per_km"];
                };
                header?: {
                    /** @description Preference */
                    Prefer?: components["parameters"]["preferReturn"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: components["requestBodies"]["activities"];
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        trace?: never;
    };
    "/public_activities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    id?: components["parameters"]["rowFilter.public_activities.id"];
                    sport_type?: components["parameters"]["rowFilter.public_activities.sport_type"];
                    title?: components["parameters"]["rowFilter.public_activities.title"];
                    started_at?: components["parameters"]["rowFilter.public_activities.started_at"];
                    ended_at?: components["parameters"]["rowFilter.public_activities.ended_at"];
                    timezone?: components["parameters"]["rowFilter.public_activities.timezone"];
                    distance_m?: components["parameters"]["rowFilter.public_activities.distance_m"];
                    duration_s?: components["parameters"]["rowFilter.public_activities.duration_s"];
                    moving_time_s?: components["parameters"]["rowFilter.public_activities.moving_time_s"];
                    elevation_gain_m?: components["parameters"]["rowFilter.public_activities.elevation_gain_m"];
                    avg_hr?: components["parameters"]["rowFilter.public_activities.avg_hr"];
                    max_hr?: components["parameters"]["rowFilter.public_activities.max_hr"];
                    avg_pace_s_per_km?: components["parameters"]["rowFilter.public_activities.avg_pace_s_per_km"];
                    /** @description Filtering Columns */
                    select?: components["parameters"]["select"];
                    /** @description Ordering */
                    order?: components["parameters"]["order"];
                    /** @description Limiting and Pagination */
                    offset?: components["parameters"]["offset"];
                    /** @description Limiting and Pagination */
                    limit?: components["parameters"]["limit"];
                };
                header?: {
                    /** @description Limiting and Pagination */
                    Range?: components["parameters"]["range"];
                    /** @description Limiting and Pagination */
                    "Range-Unit"?: components["parameters"]["rangeUnit"];
                    /** @description Preference */
                    Prefer?: components["parameters"]["preferCount"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["public_activities"][];
                        "application/vnd.pgrst.object+json;nulls=stripped": components["schemas"]["public_activities"][];
                        "application/vnd.pgrst.object+json": components["schemas"]["public_activities"][];
                        "text/csv": components["schemas"]["public_activities"][];
                    };
                };
                /** @description Partial Content */
                206: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: {
                    /** @description Filtering Columns */
                    select?: components["parameters"]["select"];
                };
                header?: {
                    /** @description Preference */
                    Prefer?: components["parameters"]["preferPost"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: components["requestBodies"]["public_activities"];
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete: {
            parameters: {
                query?: {
                    id?: components["parameters"]["rowFilter.public_activities.id"];
                    sport_type?: components["parameters"]["rowFilter.public_activities.sport_type"];
                    title?: components["parameters"]["rowFilter.public_activities.title"];
                    started_at?: components["parameters"]["rowFilter.public_activities.started_at"];
                    ended_at?: components["parameters"]["rowFilter.public_activities.ended_at"];
                    timezone?: components["parameters"]["rowFilter.public_activities.timezone"];
                    distance_m?: components["parameters"]["rowFilter.public_activities.distance_m"];
                    duration_s?: components["parameters"]["rowFilter.public_activities.duration_s"];
                    moving_time_s?: components["parameters"]["rowFilter.public_activities.moving_time_s"];
                    elevation_gain_m?: components["parameters"]["rowFilter.public_activities.elevation_gain_m"];
                    avg_hr?: components["parameters"]["rowFilter.public_activities.avg_hr"];
                    max_hr?: components["parameters"]["rowFilter.public_activities.max_hr"];
                    avg_pace_s_per_km?: components["parameters"]["rowFilter.public_activities.avg_pace_s_per_km"];
                };
                header?: {
                    /** @description Preference */
                    Prefer?: components["parameters"]["preferReturn"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch: {
            parameters: {
                query?: {
                    id?: components["parameters"]["rowFilter.public_activities.id"];
                    sport_type?: components["parameters"]["rowFilter.public_activities.sport_type"];
                    title?: components["parameters"]["rowFilter.public_activities.title"];
                    started_at?: components["parameters"]["rowFilter.public_activities.started_at"];
                    ended_at?: components["parameters"]["rowFilter.public_activities.ended_at"];
                    timezone?: components["parameters"]["rowFilter.public_activities.timezone"];
                    distance_m?: components["parameters"]["rowFilter.public_activities.distance_m"];
                    duration_s?: components["parameters"]["rowFilter.public_activities.duration_s"];
                    moving_time_s?: components["parameters"]["rowFilter.public_activities.moving_time_s"];
                    elevation_gain_m?: components["parameters"]["rowFilter.public_activities.elevation_gain_m"];
                    avg_hr?: components["parameters"]["rowFilter.public_activities.avg_hr"];
                    max_hr?: components["parameters"]["rowFilter.public_activities.max_hr"];
                    avg_pace_s_per_km?: components["parameters"]["rowFilter.public_activities.avg_pace_s_per_km"];
                };
                header?: {
                    /** @description Preference */
                    Prefer?: components["parameters"]["preferReturn"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: components["requestBodies"]["public_activities"];
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        trace?: never;
    };
    "/rpc/public_summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: {
                    /** @description Preference */
                    Prefer?: components["parameters"]["preferParams"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": Record<string, never>;
                    "application/vnd.pgrst.object+json;nulls=stripped": Record<string, never>;
                    "application/vnd.pgrst.object+json": Record<string, never>;
                    "text/csv": Record<string, never>;
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        activities: {
            /**
             * Format: uuid
             * @description Note:
             *     This is a Primary Key.<pk/>
             */
            id?: string;
            /** Format: text */
            sport_type?: string;
            /** Format: text */
            title?: string;
            /** Format: timestamp with time zone */
            started_at?: string;
            /** Format: timestamp with time zone */
            ended_at?: string;
            /** Format: text */
            timezone?: string;
            /** Format: numeric */
            distance_m?: number;
            /** Format: int32 */
            duration_s?: number;
            /** Format: int32 */
            moving_time_s?: number;
            /** Format: numeric */
            elevation_gain_m?: number;
            /** Format: int32 */
            avg_hr?: number;
            /** Format: int32 */
            max_hr?: number;
            /** Format: numeric */
            avg_pace_s_per_km?: number;
        };
        public_activities: {
            /** Format: text */
            id?: string;
            /** Format: text */
            sport_type?: string;
            /** Format: text */
            title?: string;
            /** Format: timestamp with time zone */
            started_at?: string;
            /** Format: timestamp with time zone */
            ended_at?: string;
            /** Format: text */
            timezone?: string;
            /** Format: numeric */
            distance_m?: number;
            /** Format: int32 */
            duration_s?: number;
            /** Format: int32 */
            moving_time_s?: number;
            /** Format: numeric */
            elevation_gain_m?: number;
            /** Format: int32 */
            avg_hr?: number;
            /** Format: int32 */
            max_hr?: number;
            /** Format: numeric */
            avg_pace_s_per_km?: number;
        };
    };
    responses: never;
    parameters: {
        /** @description Preference */
        preferParams: string;
        /** @description Preference */
        preferReturn: "return=representation" | "return=minimal" | "return=none";
        /** @description Preference */
        preferCount: "count=none";
        /** @description Preference */
        preferPost: "return=representation" | "return=minimal" | "return=none" | "resolution=ignore-duplicates" | "resolution=merge-duplicates";
        /** @description Filtering Columns */
        select: string;
        /** @description On Conflict */
        on_conflict: string;
        /** @description Ordering */
        order: string;
        /** @description Limiting and Pagination */
        range: string;
        /** @description Limiting and Pagination */
        rangeUnit: string;
        /** @description Limiting and Pagination */
        offset: string;
        /** @description Limiting and Pagination */
        limit: string;
        "rowFilter.activities.id": string;
        "rowFilter.activities.sport_type": string;
        "rowFilter.activities.title": string;
        "rowFilter.activities.started_at": string;
        "rowFilter.activities.ended_at": string;
        "rowFilter.activities.timezone": string;
        "rowFilter.activities.distance_m": string;
        "rowFilter.activities.duration_s": string;
        "rowFilter.activities.moving_time_s": string;
        "rowFilter.activities.elevation_gain_m": string;
        "rowFilter.activities.avg_hr": string;
        "rowFilter.activities.max_hr": string;
        "rowFilter.activities.avg_pace_s_per_km": string;
        "rowFilter.public_activities.id": string;
        "rowFilter.public_activities.sport_type": string;
        "rowFilter.public_activities.title": string;
        "rowFilter.public_activities.started_at": string;
        "rowFilter.public_activities.ended_at": string;
        "rowFilter.public_activities.timezone": string;
        "rowFilter.public_activities.distance_m": string;
        "rowFilter.public_activities.duration_s": string;
        "rowFilter.public_activities.moving_time_s": string;
        "rowFilter.public_activities.elevation_gain_m": string;
        "rowFilter.public_activities.avg_hr": string;
        "rowFilter.public_activities.max_hr": string;
        "rowFilter.public_activities.avg_pace_s_per_km": string;
    };
    requestBodies: {
        /** @description activities */
        activities: {
            content: {
                "application/json": components["schemas"]["activities"];
                "application/vnd.pgrst.object+json;nulls=stripped": components["schemas"]["activities"];
                "application/vnd.pgrst.object+json": components["schemas"]["activities"];
                "text/csv": components["schemas"]["activities"];
            };
        };
        /** @description public_activities */
        public_activities: {
            content: {
                "application/json": components["schemas"]["public_activities"];
                "application/vnd.pgrst.object+json;nulls=stripped": components["schemas"]["public_activities"];
                "application/vnd.pgrst.object+json": components["schemas"]["public_activities"];
                "text/csv": components["schemas"]["public_activities"];
            };
        };
    };
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
